language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
branches:
  only: 
    - master
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $github_token
  local_dir: public
  keep-history: true
  on:
    branch: master
before_script:
  - "npm i -g gatsby"
  - "npm i"
script:
  - "npm run test"
after_success:
  - "npm run deploy"