const tagIcons = {
  Git: ["fab", "git-alt"],
  BigCommerce: "shopping-cart",
  Node: ["fab", "node-js"],
  HTML: ["fab", "html5"],
  Firefox: ["fab", "firefox-browser"],
  WordPress: ["fab", "wordpress"],
  React: ["fab", "react"],
  Twitter: ["fab", "twitter"],
  "Raspberry Pi": ["fab", "raspberry-pi"],
  Linux: ["fab", "linux"],
  "#DevDiscuss": ["fab", "dev"],
  JavaScript: ["fab", "js"],
  "Build Log": "tools",
  Automation: "cogs",
  Tutorial: "lightbulb",
  "Open Source": "folder-open",
  Gatsby: "glass-martini-alt",
  PHP: ["fab", "php"],
  CSS: ["fab", "css3-alt"],
  CodePen: ["fab", "codepen"],
  Markdown: ["fab", "markdown"],
  Netlify: "project-diagram",
  AJAX: "cloud-download-alt",
  "Life Hacks": "hammer",
  "Material Design": "palette",
  Webpack: "box",
  Photography: "camera",
  Animation: "circle-notch",
  History: "calendar",
  Newsletter: "envelope",
  Python: ["fab", "python"],
  Shopify: ["fab", "shopify"],
  "E-Commerce": 'shopping-bag',
  "Code Snippets": 'code',
  Writing: "pencil-alt",
  "Non Profit": "tree",
  Cannabis: "cannabis",
  Career: "user-astronaut",
  Freelance: "bacon",
  DigitalOcean: ["fab", "digital-ocean"],
  Travel: "paper-plane",
  Illustrator: "bezier-curve",
  "Graphic Design": "palette",
  "Plug & Play": "plug"
}

export default tagIcons
