import { library, config } from "@fortawesome/fontawesome-svg-core"
import { fab } from "@fortawesome/free-brands-svg-icons"
import {
  faCheckSquare,
  faTag,
  faEnvelope,
  faCoffee,
  faCaretDown,
  faPalette,
  faBars,
  faArrowLeft,
  faArrowRight,
  faExternalLinkAlt,
  faUndoAlt,
  faShareAlt,
  faClock,
  faStopwatch,
  faCalendar,
  faRss,
  faShoppingCart,
  faCogs,
  faLightbulb,
  faFolderOpen,
  faGlassMartiniAlt,
  faProjectDiagram,
  faCloudDownloadAlt,
  faHammer,
  faBox,
  faCamera,
  faCircleNotch,
  faTools,
  faEllipsisH,
  faQuestionCircle,
  faShoppingBag,
  faPencilAlt,
  faTimes,
  faTree,
  faUserAstronaut,
  faSpinner,
  faCode,
  faLock,
  faBacon,
  faPaperPlane,
  faBezierCurve,
  faMoneyBill,
  faShieldAlt,
  faPlug, faGhost, 
  faList,
  faTasks, faBrain
} from "@fortawesome/free-solid-svg-icons"

config.autoAddCss = false

library.add(
  fab,
  faCheckSquare,
  faEnvelope,
  faCoffee,
  faCaretDown,
  faPalette,
  faBars,
  faArrowLeft,
  faArrowRight,
  faExternalLinkAlt,
  faUndoAlt,
  faShareAlt,
  faTag,
  faClock,
  faStopwatch,
  faCalendar,
  faRss,
  faShoppingCart,
  faCogs,
  faLightbulb,
  faFolderOpen,
  faGlassMartiniAlt,
  faProjectDiagram,
  faCloudDownloadAlt,
  faHammer,
  faBox,
  faCamera,
  faCircleNotch,
  faTools,
  faEllipsisH,
  faQuestionCircle,
  faShoppingBag,
  faPencilAlt,
  faTimes,
  faTree,
  faUserAstronaut,
  faSpinner,
  faCode,
  faLock,
  faBacon,
  faPaperPlane,
  faBezierCurve,
  faMoneyBill,
  faShieldAlt,
  faPlug, faGhost, 
  faList,
  faTasks, faBrain)
